import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import axiosInstance from '../../utils/axiosInstance';
import { ArrowLeft, Printer, CheckCircle, Clock, AlertCircle, FileText } from 'lucide-react';

const MONTHS = ['', 'January','February','March','April','May','June','July','August','September','October','November','December'];

const STATUS_CONFIG = {
  unpaid: { color: 'bg-red-100 text-red-700 border-red-200', icon: <Clock size={16}/> },
  partially_paid: { color: 'bg-orange-100 text-orange-700 border-orange-200', icon: <AlertCircle size={16}/> },
  paid: { color: 'bg-green-100 text-green-700 border-green-200', icon: <CheckCircle size={16}/> },
  overdue: { color: 'bg-red-200 text-red-800 border-red-300', icon: <AlertCircle size={16}/> },
};

export default function BillDetails() {
  const { id } = useParams();
  const [bill, setBill] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axiosInstance.get(`/bills/${id}`)
      .then(res => setBill(res.data.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="p-6">Loading bill details...</div>;
  if (!bill) return <div className="p-6 text-red-500">Bill not found.</div>;

  const statusCfg = STATUS_CONFIG[bill.status] || STATUS_CONFIG['unpaid'];

  const handleDownloadPDF = () => {
    const url = `${axiosInstance.defaults.baseURL}/reports/invoice/${id}`;
    window.open(url, '_blank');
  };

  const lineItems = [
    { label: 'Units Consumed', value: `${Number(bill.units_consumed).toFixed(2)} kWh`, highlight: false },
    { label: 'Energy Charge', sub: `${bill.units_consumed} kWh × UGX ${Number(bill.energy_charge / bill.units_consumed || 0).toFixed(2)}`, value: `UGX ${Number(bill.energy_charge).toLocaleString()}`, highlight: false },
    { label: 'Service Charge', value: `UGX ${Number(bill.service_charge).toLocaleString()}`, highlight: false },
    { label: 'Tax / VAT', value: `UGX ${Number(bill.tax_amount).toLocaleString()}`, highlight: false },
    { label: 'Previous Balance', value: `UGX ${Number(bill.previous_balance).toLocaleString()}`, highlight: Number(bill.previous_balance) > 0 },
    { label: 'Late Payment Penalty', value: `UGX ${Number(bill.penalty_amount).toLocaleString()}`, highlight: Number(bill.penalty_amount) > 0 },
  ];

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link to="/admin/bills" className="p-2 bg-white rounded-lg border border-border hover:bg-gray-50 text-gray-500">
            <ArrowLeft size={20}/>
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{bill.bill_number}</h1>
            <p className="text-sm text-gray-500">Bill for {MONTHS[bill.billing_month]} {bill.billing_year}</p>
          </div>
        </div>
        <div className="flex items-center space-x-3">
          <span className={`inline-flex items-center space-x-1.5 text-sm px-3 py-1.5 rounded-full font-medium border ${statusCfg.color}`}>
            {statusCfg.icon}<span>{bill.status.replace('_', ' ').toUpperCase()}</span>
          </span>
          <button onClick={handleDownloadPDF} className="flex items-center space-x-2 bg-primary text-white px-4 py-2 rounded-lg text-sm hover:bg-primary-dark transition-colors shadow-sm">
            <FileText size={16}/><span>Download PDF</span>
          </button>
          <button onClick={() => window.print()} className="flex items-center space-x-2 bg-white border border-border text-gray-600 px-4 py-2 rounded-lg text-sm hover:bg-gray-50 transition-colors">
            <Printer size={16}/><span>Print</span>
          </button>
        </div>
      </div>

      {/* Customer & Meta Info */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="bg-white rounded-xl shadow-sm border border-border p-5 space-y-2">
          <p className="text-xs text-gray-500 uppercase tracking-widest font-medium">Customer</p>
          <p className="font-bold text-gray-900 text-lg">{bill.customer_name}</p>
          <p className="text-sm text-gray-500">{bill.customer_number}</p>
          <p className="text-xs text-gray-400 capitalize">{bill.category} Account</p>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-border p-5 space-y-2">
          <p className="text-xs text-gray-500 uppercase tracking-widest font-medium">Meter Details</p>
          <p className="font-bold text-gray-900">{bill.meter_number}</p>
          <p className="text-sm text-gray-500">Due: <span className="font-semibold text-gray-800">{new Date(bill.due_date).toLocaleDateString()}</span></p>
          <p className="text-xs text-gray-400">Generated by: {bill.generated_by_name || 'System'}</p>
        </div>
      </div>

      {/* Bill Breakdown */}
      <div className="bg-white rounded-xl shadow-sm border border-border overflow-x-auto">
        <div className="p-5 border-b border-border bg-gray-50">
          <h2 className="font-semibold text-gray-800">Bill Breakdown</h2>
        </div>
        <div className="divide-y divide-border">
          {lineItems.map((item, i) => (
            <div key={i} className={`flex justify-between items-center px-5 py-3 ${item.highlight ? 'bg-red-50' : ''}`}>
              <div>
                <span className="text-sm font-medium text-gray-700">{item.label}</span>
                {item.sub && <p className="text-xs text-gray-400 mt-0.5">{item.sub}</p>}
              </div>
              <span className={`text-sm font-semibold ${item.highlight ? 'text-red-600' : 'text-gray-900'}`}>{item.value}</span>
            </div>
          ))}
          {/* Total Row */}
          <div className="flex justify-between items-center px-5 py-4 bg-sidebar text-white">
            <span className="font-bold text-lg">TOTAL PAYABLE</span>
            <span className="font-bold text-xl">UGX {Number(bill.total_amount).toLocaleString()}</span>
          </div>
          <div className="flex justify-between items-center px-5 py-3 bg-gray-50">
            <span className="text-sm text-gray-600">Amount Paid</span>
            <span className="text-sm font-semibold text-green-600">UGX {Number(bill.amount_paid).toLocaleString()}</span>
          </div>
          <div className="flex justify-between items-center px-5 py-3">
            <span className="text-sm font-bold text-gray-800">Balance Due</span>
            <span className={`text-lg font-bold ${Number(bill.balance_due) > 0 ? 'text-red-600' : 'text-green-600'}`}>UGX {Number(bill.balance_due).toLocaleString()}</span>
          </div>
        </div>
      </div>
    </div>
  );
}
